"use client";

import React, { useEffect, useState } from "react";
import { useTheme } from "next-themes";
import styles from "./styles.module.css";

export function ThemeToggle() {
  const [mounted, setMounted] = useState(false);
  const { theme, setTheme } = useTheme();

  // Wait until mounted to prevent hydration mismatch
  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return <div className="h-[30px] w-[60px]" />; // Placeholder to keep layout stable
  }

  const isDark = theme === "dark";

  return (
    <div className={styles.container}>
      <input
        type="checkbox"
        id="theme-checkbox"
        className={styles.checkbox}
        checked={isDark}
        onChange={() => setTheme(isDark ? "light" : "dark")}
      />
      <label htmlFor="theme-checkbox" className={styles.label}>
        {/* The ball is generated by the ::before pseudo-element in CSS */}
      </label>
    </div>
  );
}